### ISSUE TITLE
Can you share architectural ideas of boards.aughie.org ？

### ISSUE THREAD

**Issue by codeflitting** [agostbiro/blog.agostbiro.net#1]
I am also a machine learning developer, and I am very interested in boards.aughie.org. I also want to build one within our team,  can you share some architectural ideas？

**Comment by agostbiro** [comment]
Hi @codeflitting,

Aughie Boards worked by enumerating all the possible API calls for a TensorBoard log dir, saving the results as files, and then serving the client's API calls from static storage. However, you don't need to implement this yourself, as the good folks on the TensorBoard team now offer it as a service themselves: https://tensorboard.dev/

Best,
Agost
